services:
  postgres:
    image: postgres:17-alpine
    container_name: wikiguessr-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wikiguessr
      POSTGRES_PASSWORD: wikiguessr
      POSTGRES_DB: wikiguessr
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
